version: '1.0'

services:
  database:
    image: mysql:8.0
    ports:
      - "3310:3306"
    container_name: BrainBlitz
#    volumes:
#      - dbdata:/var/lib/mysql
#    restart: always
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: brainBlitz_db
      MYSQL_USER: bbGame
      MYSQL_PASSWORD: root

volumes:
  dbdata: